/********************************************************************
* MakePlotsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MakePlotsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableMakePlotsDict();
extern void G__cpp_setup_inheritanceMakePlotsDict();
extern void G__cpp_setup_typetableMakePlotsDict();
extern void G__cpp_setup_memvarMakePlotsDict();
extern void G__cpp_setup_globalMakePlotsDict();
extern void G__cpp_setup_memfuncMakePlotsDict();
extern void G__cpp_setup_funcMakePlotsDict();
extern void G__set_cpp_environmentMakePlotsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MakePlots.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MakePlotsDictLN_TString;
extern G__linked_taginfo G__MakePlotsDictLN_TDirectory;
extern G__linked_taginfo G__MakePlotsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MakePlotsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MakePlotsDictLN_TH1;
extern G__linked_taginfo G__MakePlotsDictLN_MakePlots;

/* STUB derived class for protected member access */
